version: "3.3"
services:
  magicpack:
    image: alexswki/magicpack
    network_mode: host
    restart: always
    container_name: magicpack
    volumes:
      - ./computers.json:/magicpack/computers.json
      - ./.env:/magicpack/.env.local
